# Generated by Django 5.2.15 on 2026-09-04 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainer', '0037_curso_es_gratuito_curso_precio_ars_curso_precio_usd_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('precio_ars', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('incluye_todos_los_cursos', models.BooleanField(default=False, help_text='Si está activo, este plan da acceso a TODOS los cursos pagos sin importar compra individual (ver pagos/access.py:tiene_acceso()).')),
                ('activo', models.BooleanField(default=True, help_text='Solo los planes activos se ofrecen en checkout -- desactivar un plan NO corta el acceso de quienes ya están suscriptos a él (tiene_acceso() nunca mira este campo, solo Suscripcion.fecha_fin_periodo_actual). Mismo criterio que Curso.activo en trainer/models.py.')),
                ('mercadopago_plan_id', models.CharField(blank=True, help_text='ID del plan de preaprobación ya creado del lado de MercadoPago (preapproval_plan_id).', max_length=100)),
                ('paypal_plan_id', models.CharField(blank=True, help_text='ID del plan de facturación ya creado del lado de PayPal (Billing Plan id).', max_length=100)),
                ('features', models.ManyToManyField(blank=True, related_name='planes', to='pagos.feature')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
            },
        ),
        migrations.CreateModel(
            name='CompraIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso_codigo', models.CharField(help_text='Copia de Curso.codigo (mismo max_length que ese campo) al momento de la compra. Es la clave real de acceso -- ver curso_codigo vs curso más abajo.', max_length=140)),
                ('proveedor', models.CharField(choices=[('mercadopago', 'MercadoPago'), ('paypal', 'PayPal')], max_length=20)),
                ('id_externo', models.CharField(help_text='ID del pago/orden en el proveedor (MercadoPago payment id / PayPal order id).', max_length=100, unique=True)),
                ('moneda', models.CharField(choices=[('ARS', 'ARS'), ('USD', 'USD')], max_length=3)),
                ('precio_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(blank=True, help_text='Referencia de conveniencia a la fila Curso específica elegida en el checkout, solo para mostrar nombre/idioma en el admin. La fuente de verdad de acceso es curso_codigo, no este campo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_individuales', to='trainer.curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_individuales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compra Individual',
                'verbose_name_plural': 'Compras Individuales',
                'unique_together': {('usuario', 'curso_codigo')},
            },
        ),
        migrations.CreateModel(
            name='EventoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(choices=[('mercadopago', 'MercadoPago'), ('paypal', 'PayPal')], max_length=20)),
                ('tipo_evento', models.CharField(help_text="Tipo de evento tal cual lo manda el proveedor (ej. 'payment.updated', 'BILLING.SUBSCRIPTION.CANCELLED'). CharField libre, sin choices -- cada proveedor tiene su propio catálogo y puede sumar tipos nuevos sin necesitar una migración acá.", max_length=80)),
                ('id_evento_externo', models.CharField(blank=True, db_index=True, help_text='ID del evento/notificación del proveedor, usado para el chequeo de idempotencia antes de aplicar efectos (ver pagos/webhooks.py). NO es unique a propósito -- cada entrega recibida se loguea, incluso reintentos/duplicados del proveedor; lo idempotente es el EFECTO sobre Suscripcion/CompraIndividual, no este log.', max_length=150)),
                ('payload_raw', models.JSONField(help_text='Body crudo del webhook, completo, sin transformar -- para reconstruir manualmente qué pasó ante cualquier duda, sin depender del dashboard del proveedor.')),
                ('procesado_ok', models.BooleanField(default=False)),
                ('requiere_atencion', models.BooleanField(default=False, help_text='True solo para firma inválida o proveedor no configurado -- NUNCA para duplicados (tráfico esperado). Dispara mail_admins() en el momento (ver pagos/webhooks.py) y es lo que filtra el management command reporte_eventos_fallidos.')),
                ('detalle', models.CharField(blank=True, help_text="Texto corto de diagnóstico: motivo de rechazo de firma, 'duplicado, no-op', qué campo se actualizó, etc.", max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_pago', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de Pago',
                'verbose_name_plural': 'Eventos de Pago',
                'indexes': [models.Index(fields=['proveedor', 'tipo_evento', 'id_evento_externo'], name='pagos_event_proveed_da7606_idx'), models.Index(fields=['requiere_atencion', 'creado_en'], name='pagos_event_requier_4f8d7b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(choices=[('mercadopago', 'MercadoPago'), ('paypal', 'PayPal')], max_length=20)),
                ('id_externo', models.CharField(help_text='ID de la suscripción en el proveedor (MercadoPago preapproval id / PayPal subscription id). Estable a través de renovaciones.', max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('pago_fallido', 'Pago fallido'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada')], default='activa', help_text='Solo para diagnóstico/admin -- NUNCA usar este campo para decidir acceso. El acceso real se calcula SIEMPRE comparando fecha_fin_periodo_actual contra ahora (ver pagos/access.py:tiene_acceso()). Cancelar no corta el acceso al instante; un pago fallido nunca lo otorga, pero tampoco recorta un período ya pagado.', max_length=20)),
                ('moneda', models.CharField(choices=[('ARS', 'ARS'), ('USD', 'USD')], max_length=3)),
                ('precio_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin_periodo_actual', models.DateTimeField(help_text='Fin del período ya pagado. ÚNICO campo que tiene_acceso() consulta para decidir acceso por suscripción -- se actualiza en cada renovación exitosa, NO se toca al cancelar (la cancelación solo deja de renovar a futuro) ni al fallar un pago (un pago fallido no recorta un período ya pagado, solo impide que se extienda).')),
                ('cancelada_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='pagos.plan')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'indexes': [models.Index(fields=['usuario', 'fecha_fin_periodo_actual'], name='pagos_suscr_usuario_e6ef78_idx')],
            },
        ),
    ]
