# Generated by Django 5.2.15 on 2026-06-08 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('clef', models.CharField(default='treble', max_length=20)),
                ('min_note', models.CharField(default='C4', max_length=5)),
                ('max_note', models.CharField(default='G5', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presented_note', models.CharField(max_length=5)),
                ('guessed_note', models.CharField(max_length=5)),
                ('is_correct', models.BooleanField()),
                ('response_time_ms', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('total_points', models.IntegerField(default=0)),
                ('max_streak', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('total_answers', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
