# Generated by Django 5.2.15 on 2026-06-08

from django.db import migrations

def seed_games(apps, schema_editor):
    Game = apps.get_model('trainer', 'Game')
    Game.objects.get_or_create(
        slug='notas',
        defaults={
            'name': 'Identificación de Notas',
            'description': 'Aprende a reconocer rápidamente notas en el pentagrama.'
        }
    )
    Game.objects.get_or_create(
        slug='intervalos',
        defaults={
            'name': 'Intervalos',
            'description': 'Aprende a identificar distancias musicales entre dos notas.'
        }
    )
    Game.objects.get_or_create(
        slug='intervalos-auditivos',
        defaults={
            'name': 'Intervalos Auditivos',
            'description': 'Entrena tu oído para reconocer intervalos musicales.'
        }
    )

def remove_games(apps, schema_editor):
    Game = apps.get_model('trainer', 'Game')
    Game.objects.filter(slug__in=['notas', 'intervalos', 'intervalos-auditivos']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_games, reverse_code=remove_games),
    ]
