# Generated by Django 5.2.15 on 2026-06-08 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_achievement_game_order_game_unlock_required_accuracy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='unlock_required_accuracy',
            new_name='recommended_accuracy',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='unlock_required_attempts',
            new_name='recommended_attempts',
        ),
    ]
