# Generated by Django 5.2.15 on 2026-06-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_rename_unlock_required_accuracy_game_recommended_accuracy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('time_signature', models.CharField(default='4/4', max_length=10)),
                ('key_signature', models.CharField(blank=True, max_length=50, null=True)),
                ('difficulty', models.IntegerField(default=1, help_text='1: Principiante, 2: Intermedio, 3: Avanzado')),
                ('xml_content', models.TextField(help_text='Contenido en formato MusicXML')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
