# Generated by Django 5.2.15 on 2026-06-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0005_piece'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Se puede extraer automáticamente del MusicXML', max_length=100)),
                ('composer', models.CharField(blank=True, help_text='Se puede extraer automáticamente del MusicXML', max_length=100)),
                ('difficulty', models.IntegerField(default=1)),
                ('xml_file', models.FileField(upload_to='partituras/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
