# Generated by Django 5.2.15 on 2026-06-12 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0006_sheetmusic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('goal_type', models.CharField(choices=[('TIME', 'Tiempo de Estudio'), ('PIECES', 'Partituras Completadas')], max_length=20)),
                ('target_value', models.IntegerField(help_text='Ej: 10 para 10 minutos')),
            ],
        ),
        migrations.AddField(
            model_name='sheetmusic',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='sheet_musics', to='trainer.collection'),
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('bpm_used', models.IntegerField(default=100)),
                ('play_count', models.IntegerField(default=0)),
                ('sheet_music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.sheetmusic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sheet_music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='trainer.sheetmusic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'sheet_music')},
            },
        ),
        migrations.CreateModel(
            name='SheetMusicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_time_seconds', models.IntegerField(default=0)),
                ('total_plays', models.IntegerField(default=0)),
                ('completion_percentage', models.IntegerField(default=0)),
                ('last_practiced', models.DateTimeField(auto_now=True)),
                ('sheet_music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.sheetmusic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'sheet_music')},
            },
        ),
        migrations.CreateModel(
            name='UserDailyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('current_value', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.dailygoal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'goal', 'date')},
            },
        ),
    ]
