# Generated by Django 4.2.7 on 2026-06-12 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainer', '0007_collection_dailygoal_sheetmusic_collections_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='studysession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_sessions_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_study_time_day',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SheetNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sheet_music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.sheetmusic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SheetMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.IntegerField()),
                ('text', models.CharField(max_length=200)),
                ('color', models.CharField(default='blue', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sheet_music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.sheetmusic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_markers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='session_audio/')),
                ('evaluation_score', models.IntegerField(blank=True, null=True)),
                ('feedback_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio_eval', to='trainer.studysession')),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trainer.playlist')),
                ('sheet_music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.sheetmusic')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
