# Generated by Django 5.2.15 on 2026-06-12 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0008_playlist_studysession_end_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RehearsalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_measure', models.IntegerField(default=1)),
                ('end_measure', models.IntegerField(default=1)),
                ('start_bpm', models.IntegerField(default=60)),
                ('end_bpm', models.IntegerField(default=100)),
                ('bpm_step', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sheet_music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.sheetmusic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehearsal_configs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RehearsalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetitions_done', models.IntegerField(default=0)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('max_bpm_reached', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rehearsal_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainer.rehearsalconfig')),
                ('sheet_music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.sheetmusic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehearsal_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
