# Generated by Django 5.2.15 on 2026-06-14 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0009_rehearsalconfig_rehearsallog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicalProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('last_practice', models.DateTimeField(auto_now=True)),
                ('time_invested_seconds', models.IntegerField(default=0)),
                ('max_bpm_reached', models.IntegerField(default=0)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('last_measure', models.IntegerField(default=1)),
                ('last_tempo', models.IntegerField(default=60)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('COMPLETED', 'Completado')], default='ACTIVE', max_length=20)),
                ('sheet_music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.sheetmusic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('BPM', 'Llegar a BPM Objetivo'), ('TIME', 'Practicar Tiempo (min)'), ('COMPLETE', 'Completar Obra')], max_length=20)),
                ('target_value', models.IntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='trainer.musicalproject')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_measure', models.IntegerField()),
                ('end_measure', models.IntegerField()),
                ('status', models.CharField(choices=[('MASTERED', 'Dominado'), ('IN_PROGRESS', 'En Progreso'), ('NEEDS_PRACTICE', 'Necesita Práctica')], default='IN_PROGRESS', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='trainer.musicalproject')),
            ],
            options={
                'ordering': ['start_measure'],
            },
        ),
    ]
