# Generated by Django 5.2.15 on 2026-06-14 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0010_musicalproject_projectgoal_projectsection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MidiChordStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chord_name', models.CharField(max_length=50)),
                ('correct_count', models.IntegerField(default=0)),
                ('incorrect_count', models.IntegerField(default=0)),
                ('avg_response_time_ms', models.IntegerField(default=0)),
                ('is_mastered', models.BooleanField(default=False)),
                ('is_problematic', models.BooleanField(default=False)),
                ('last_played', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midi_chord_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MidiGameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(default='chord_identification', max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('xp_earned', models.IntegerField(default=0)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midi_game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
