# Generated by Django 5.2.15 on 2026-07-09 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0011_midichordstat_midigamesession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('score_file', models.FileField(help_text='Formatos: .mid, .midi, .musicxml, .mxl', upload_to='orquestador/scores/')),
                ('analysis_data', models.JSONField(blank=True, help_text='Reporte final estructurado por el agente de IA y music21', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_analyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
