# Generated by Django 5.2.15 on 2026-07-27 02:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0012_scoreanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='creditos_analisis',
            field=models.IntegerField(default=30, help_text='Créditos mensuales del analizador de partituras. Se resetean automáticamente cada 30 días.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='creditos_bonus',
            field=models.IntegerField(default=0, help_text='Créditos adicionales cargados manualmente o comprados. No se resetean ni vencen.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fecha_ultimo_reset',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
