# Generated by Django 5.2.15 on 2026-07-27 02:57

from django.db import migrations, models


def zero_out_creditos_analisis(apps, schema_editor):
    """
    Los perfiles existentes recibieron 30 créditos por un default incorrecto,
    no porque un admin se los haya asignado. Se corrige a 0 para todos.
    """
    UserProfile = apps.get_model('trainer', 'UserProfile')
    UserProfile.objects.update(creditos_analisis=0)


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0013_userprofile_creditos_analisis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='fecha_ultimo_reset',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='creditos_analisis',
            field=models.IntegerField(default=0, help_text='Créditos del analizador de partituras asignados manualmente por el admin. No se otorgan automáticamente.'),
        ),
        migrations.RunPython(zero_out_creditos_analisis, migrations.RunPython.noop),
    ]
