# Generated by Django 5.2.15 on 2026-07-28 00:28

import django.db.models.deletion
import trainer.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0014_remove_userprofile_fecha_ultimo_reset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreanalysis',
            name='share_token',
            field=models.CharField(blank=True, db_index=True, help_text='Token aleatorio para el link público de solo lectura. Null = sin compartir.', max_length=43, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='scoreanalysis',
            name='version_de',
            field=models.ForeignKey(blank=True, help_text='Análisis anterior del que este es una nueva versión (marcado explícitamente por el usuario al subir).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versiones', to='trainer.scoreanalysis'),
        ),
        migrations.AlterField(
            model_name='scoreanalysis',
            name='score_file',
            field=models.FileField(help_text='Formatos: .mid, .midi, .musicxml, .mxl. Se cifra en disco con Fernet.', storage=trainer.storage.EncryptedFileSystemStorage(), upload_to='orquestador/scores/'),
        ),
    ]
