# Generated by Django 5.2.15 on 2026-08-02 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0015_scoreanalysis_share_token_scoreanalysis_version_de_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FragmentoOrquestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.FileField(help_text='Formatos: .musicxml, .xml, .mxl. Piano (una o dos manos).', upload_to='orquestacion_ejercicios/')),
                ('activo', models.BooleanField(default=True, help_text='Solo los fragmentos activos aparecen en el listado del ejercicio.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fragmentos_orquestacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
