# Generated by Django 5.2.15 on 2026-08-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0016_fragmentoorquestacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreanalysis',
            name='cache_creation_input_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoreanalysis',
            name='cache_read_input_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoreanalysis',
            name='creditos_cobrados',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoreanalysis',
            name='input_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoreanalysis',
            name='output_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoreanalysis',
            name='puntaje_obra',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
