# Generated by Django 5.2.15 on 2026-08-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0017_scoreanalysis_cache_creation_input_tokens_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': 'Logro', 'verbose_name_plural': 'Logros'},
        ),
        migrations.AlterModelOptions(
            name='attempt',
            options={'verbose_name': 'Intento de Juego', 'verbose_name_plural': 'Intentos de Juego'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Colección de Partituras', 'verbose_name_plural': 'Colecciones de Partituras'},
        ),
        migrations.AlterModelOptions(
            name='dailygoal',
            options={'verbose_name': 'Meta Diaria (plantilla)', 'verbose_name_plural': 'Metas Diarias (plantilla)'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Favorito de Biblioteca', 'verbose_name_plural': 'Favoritos de Biblioteca'},
        ),
        migrations.AlterModelOptions(
            name='fragmentoorquestacion',
            options={'verbose_name': 'Fragmento (Ejercicio de Orquestación)', 'verbose_name_plural': 'Fragmentos (Ejercicio de Orquestación)'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Juego (Entrenador)', 'verbose_name_plural': 'Juegos (Entrenador)'},
        ),
        migrations.AlterModelOptions(
            name='midichordstat',
            options={'verbose_name': 'Estadística de Acorde MIDI', 'verbose_name_plural': 'Estadísticas de Acordes MIDI'},
        ),
        migrations.AlterModelOptions(
            name='midigamesession',
            options={'verbose_name': 'Sesión de Juego MIDI', 'verbose_name_plural': 'Sesiones de Juego MIDI'},
        ),
        migrations.AlterModelOptions(
            name='musicalproject',
            options={'verbose_name': 'Proyecto Musical', 'verbose_name_plural': 'Proyectos Musicales'},
        ),
        migrations.AlterModelOptions(
            name='piece',
            options={'verbose_name': 'Partitura de Lectura (Entrenador)', 'verbose_name_plural': 'Partituras de Lectura (Entrenador)'},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'verbose_name': 'Playlist', 'verbose_name_plural': 'Playlists'},
        ),
        migrations.AlterModelOptions(
            name='playlistsheet',
            options={'ordering': ['order'], 'verbose_name': 'Partitura en Playlist', 'verbose_name_plural': 'Partituras en Playlist'},
        ),
        migrations.AlterModelOptions(
            name='projectgoal',
            options={'verbose_name': 'Objetivo de Proyecto', 'verbose_name_plural': 'Objetivos de Proyecto'},
        ),
        migrations.AlterModelOptions(
            name='projectsection',
            options={'ordering': ['start_measure'], 'verbose_name': 'Sección de Proyecto', 'verbose_name_plural': 'Secciones de Proyecto'},
        ),
        migrations.AlterModelOptions(
            name='rehearsalconfig',
            options={'verbose_name': 'Configuración de Ensayo', 'verbose_name_plural': 'Configuraciones de Ensayo'},
        ),
        migrations.AlterModelOptions(
            name='rehearsallog',
            options={'verbose_name': 'Registro de Ensayo', 'verbose_name_plural': 'Registros de Ensayo'},
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'verbose_name': 'Puntaje de Juego', 'verbose_name_plural': 'Puntajes de Juego'},
        ),
        migrations.AlterModelOptions(
            name='scoreanalysis',
            options={'verbose_name': 'Análisis de Orquestación (Director de Estudio)', 'verbose_name_plural': 'Análisis de Orquestación (Director de Estudio)'},
        ),
        migrations.AlterModelOptions(
            name='sessionaudio',
            options={'verbose_name': 'Audio de Sesión (evaluación)', 'verbose_name_plural': 'Audios de Sesión (evaluación)'},
        ),
        migrations.AlterModelOptions(
            name='sheetmarker',
            options={'verbose_name': 'Marcador de Partitura', 'verbose_name_plural': 'Marcadores de Partitura'},
        ),
        migrations.AlterModelOptions(
            name='sheetmusic',
            options={'verbose_name': 'Partitura (Biblioteca)', 'verbose_name_plural': 'Partituras (Biblioteca)'},
        ),
        migrations.AlterModelOptions(
            name='sheetmusicprogress',
            options={'verbose_name': 'Progreso de Partitura', 'verbose_name_plural': 'Progresos de Partitura'},
        ),
        migrations.AlterModelOptions(
            name='sheetnote',
            options={'verbose_name': 'Anotación de Partitura', 'verbose_name_plural': 'Anotaciones de Partitura'},
        ),
        migrations.AlterModelOptions(
            name='studysession',
            options={'verbose_name': 'Sesión de Estudio', 'verbose_name_plural': 'Sesiones de Estudio'},
        ),
        migrations.AlterModelOptions(
            name='userachievement',
            options={'verbose_name': 'Logro Obtenido', 'verbose_name_plural': 'Logros Obtenidos'},
        ),
        migrations.AlterModelOptions(
            name='userdailygoal',
            options={'verbose_name': 'Meta Diaria de Usuario', 'verbose_name_plural': 'Metas Diarias de Usuario'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuario'},
        ),
        migrations.AlterField(
            model_name='fragmentoorquestacion',
            name='archivo',
            field=models.FileField(help_text='Formatos: .musicxml, .xml, .mxl. Piano (una o dos manos). Subí acá el fragmento para el Ejercicio de Orquestación -- no es la Biblioteca de Partituras.', upload_to='orquestacion_ejercicios/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(help_text='Tiene que coincidir con el slug ya cableado en las URLs del Entrenador -- crear un Game nuevo acá no crea una página nueva sola.', unique=True),
        ),
        migrations.AlterField(
            model_name='piece',
            name='xml_content',
            field=models.TextField(help_text="Contenido MusicXML pegado como texto. Alimenta el juego 'Lectura Musical' del Entrenador -- esto NO aparece en la Biblioteca de Partituras (para eso usá 'Partitura (Biblioteca)')."),
        ),
        migrations.AlterField(
            model_name='sheetmusic',
            name='xml_file',
            field=models.FileField(help_text='Subí acá el archivo (MusicXML o .mxl comprimido) -- va a aparecer en la Biblioteca de Partituras del sitio.', upload_to='partituras/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='creditos_analisis',
            field=models.IntegerField(default=0, help_text='Créditos del Director de Estudio (analizador de partituras con IA) asignados manualmente por el admin. No se otorgan automáticamente.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='creditos_bonus',
            field=models.IntegerField(default=0, help_text='Créditos adicionales del Director de Estudio cargados manualmente o comprados. No se resetean ni vencen.'),
        ),
    ]
