# Generated by Django 5.2.15 on 2026-08-23 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0018_alter_achievement_options_alter_attempt_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion_corta', models.CharField(blank=True, max_length=300)),
                ('activo', models.BooleanField(default=True, help_text='Solo los cursos activos aparecen listados para los usuarios.')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Orden dentro del curso Y etiqueta visible ("Grado 0", "Grado 1", ...).')),
                ('titulo', models.CharField(help_text='Ej: "Fundamentos de lectura".', max_length=200)),
                ('activo', models.BooleanField(default=True, help_text='Solo los grados activos aparecen listados para los usuarios.')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grados', to='trainer.curso')),
            ],
            options={
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
                'ordering': ['numero'],
                'unique_together': {('curso', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden dentro del grado.')),
                ('slug', models.SlugField(help_text='Se escribe a mano, no se autogenera (misma convención que Game.slug/Achievement.slug/Collection.slug). Único dentro del grado -- se usa en la URL del tema.')),
                ('activo', models.BooleanField(default=True, help_text='Solo los temas activos son accesibles para los usuarios.')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='trainer.grado')),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'ordering': ['orden'],
                'unique_together': {('grado', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='BloqueContenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('tipo', models.CharField(choices=[('TEXTO', 'Texto'), ('EJEMPLO_PARTITURA', 'Ejemplo de partitura'), ('PRACTICA', 'Práctica')], max_length=20)),
                ('texto_markdown', models.TextField(blank=True, help_text='Fuente Markdown (nunca HTML crudo). Se sanitiza y renderiza en el detalle del tema.')),
                ('contexto_ejemplo', models.CharField(blank=True, help_text='Texto corto opcional arriba del ejemplo, ej: "En este ejemplo, fijate cómo...".', max_length=300)),
                ('practica_texto', models.CharField(blank=True, help_text='Ej: "Practicá esto en Identificación de Notas". Requerido cuando el tipo es Práctica.', max_length=300)),
                ('practica_url', models.CharField(blank=True, help_text='URL/path opcional escrito a mano hacia una página existente (ej: /juego/notas/). Si queda vacío, se muestra como texto plano sin link. Deliberadamente NO es una FK a Game ni a nada más.', max_length=300)),
                ('fragmento_orquestacion', models.ForeignKey(blank=True, help_text="Fragmento del Ejercicio de Orquestación a mostrar como ejemplo. Exactamente uno entre esto y 'sheet music' cuando el tipo es Ejemplo de partitura.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloques_curso', to='trainer.fragmentoorquestacion')),
                ('sheet_music', models.ForeignKey(blank=True, help_text="Partitura de la Biblioteca a mostrar como ejemplo. Exactamente uno entre esto y 'fragmento orquestación' cuando el tipo es Ejemplo de partitura.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloques_curso', to='trainer.sheetmusic')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='trainer.tema')),
            ],
            options={
                'verbose_name': 'Bloque de Contenido',
                'verbose_name_plural': 'Bloques de Contenido',
                'ordering': ['orden'],
            },
        ),
    ]
