# Generated by Django 5.2.15 on 2026-08-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0026_game_description_en_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloquecontenido',
            name='mostrar_compositor',
            field=models.BooleanField(default=True, help_text='Si está destildado, oculta el subtítulo/compositor/arreglador embebidos en el archivo.'),
        ),
        migrations.AddField(
            model_name='bloquecontenido',
            name='mostrar_letra',
            field=models.BooleanField(default=True, help_text='Si está destildado, oculta la letra (lyrics) que venga incluida en la partitura.'),
        ),
        migrations.AddField(
            model_name='bloquecontenido',
            name='mostrar_nombre_instrumento',
            field=models.BooleanField(default=True, help_text='Si está destildado, oculta el nombre del instrumento junto al pentagrama.'),
        ),
    ]
