# Generated by Django 5.2.15 on 2026-08-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0027_bloquecontenido_mostrar_compositor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloquecontenido',
            name='contexto_ejemplo_en',
            field=models.CharField(blank=True, help_text='Versión en inglés. Si queda vacío, se muestra el texto en español también con idioma inglés activo.', max_length=300),
        ),
        migrations.AddField(
            model_name='bloquecontenido',
            name='practica_texto_en',
            field=models.CharField(blank=True, help_text='Versión en inglés. Si queda vacío, se muestra el texto en español también con idioma inglés activo.', max_length=300),
        ),
        migrations.AddField(
            model_name='bloquecontenido',
            name='practica_url_en',
            field=models.CharField(blank=True, help_text='Versión en inglés del path, SOLO si difiere del de arriba -- casi siempre porque necesita el prefijo /en/ (ver i18n_patterns en config/urls.py: una URL sin prefijo fuerza español sin importar el idioma activo). Si queda vacío, se usa el mismo path de arriba tal cual.', max_length=300),
        ),
        migrations.AddField(
            model_name='bloquecontenido',
            name='texto_markdown_en',
            field=models.TextField(blank=True, help_text='Fuente Markdown en inglés. Si queda vacío, se muestra el texto en español también con idioma inglés activo.'),
        ),
    ]
