# Generated by Django 5.2.15 on 2026-08-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0028_bloquecontenido_contexto_ejemplo_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grado',
            name='titulo_en',
            field=models.CharField(blank=True, help_text='Versión en inglés. Si queda vacío, se muestra el título en español también con idioma inglés activo.', max_length=200),
        ),
        migrations.AddField(
            model_name='tema',
            name='titulo_en',
            field=models.CharField(blank=True, help_text='Versión en inglés. Si queda vacío, se muestra el título en español también con idioma inglés activo.', max_length=200),
        ),
    ]
