# Generated by Django 5.2.15 on 2026-08-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0029_grado_titulo_en_tema_titulo_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='descripcion_corta_en',
            field=models.CharField(blank=True, help_text='Versión en inglés. Si queda vacío, se muestra la descripción en español también con idioma inglés activo.', max_length=300),
        ),
        migrations.AddField(
            model_name='curso',
            name='nombre_en',
            field=models.CharField(blank=True, help_text='Versión en inglés. Si queda vacío, se muestra el nombre en español también con idioma inglés activo.', max_length=200),
        ),
    ]
