# Generated by Django 5.2.15 on 2026-08-31 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0030_curso_descripcion_corta_en_curso_nombre_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloquecontenido',
            name='contexto_imagen',
            field=models.CharField(blank=True, help_text='Pie de imagen (también se usa como texto alternativo/accesibilidad).', max_length=300),
        ),
        migrations.AddField(
            model_name='bloquecontenido',
            name='contexto_imagen_en',
            field=models.CharField(blank=True, help_text='Versión en inglés. Si queda vacío, se muestra el texto en español también con idioma inglés activo.', max_length=300),
        ),
        migrations.AddField(
            model_name='bloquecontenido',
            name='imagen',
            field=models.FileField(blank=True, help_text='PNG, JPG o SVG -- para diagramas/fotos que no se pueden representar como MusicXML. Requerido cuando el tipo es Imagen.', null=True, upload_to='cursos_imagenes/'),
        ),
        migrations.AlterField(
            model_name='bloquecontenido',
            name='tipo',
            field=models.CharField(choices=[('TEXTO', 'Texto'), ('EJEMPLO_PARTITURA', 'Ejemplo de partitura'), ('PRACTICA', 'Práctica'), ('IMAGEN', 'Imagen')], max_length=20),
        ),
    ]
