# Generated by Django 5.2.15 on 2026-09-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0031_bloquecontenido_contexto_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloquecontenido',
            name='contexto_video',
            field=models.CharField(blank=True, help_text='Texto corto opcional arriba del video.', max_length=300),
        ),
        migrations.AddField(
            model_name='bloquecontenido',
            name='contexto_video_en',
            field=models.CharField(blank=True, help_text='Versión en inglés. Si queda vacío, se muestra el texto en español también con idioma inglés activo.', max_length=300),
        ),
        migrations.AddField(
            model_name='bloquecontenido',
            name='video_archivo',
            field=models.FileField(blank=True, help_text='MP4 (recomendado) o WebM -- son los únicos formatos que reproducen todos los navegadores sin conversión. AVI/MOV/MKV no van a andar aunque los subas. Requerido cuando la fuente es Archivo subido.', null=True, upload_to='cursos_videos/'),
        ),
        migrations.AddField(
            model_name='bloquecontenido',
            name='video_embed_url',
            field=models.CharField(blank=True, help_text='Pegá el link tal cual lo copiaste del navegador (youtube.com/watch?v=..., youtu.be/..., vimeo.com/...). Se convierte solo al formato de embed restringido. Requerido cuando la fuente es YouTube/Vimeo.', max_length=500),
        ),
        migrations.AddField(
            model_name='bloquecontenido',
            name='video_fuente',
            field=models.CharField(blank=True, choices=[('ARCHIVO', 'Archivo subido (MP4/WebM)'), ('EMBED', 'YouTube / Vimeo')], help_text='Requerido cuando el tipo es Video.', max_length=20),
        ),
        migrations.AlterField(
            model_name='bloquecontenido',
            name='tipo',
            field=models.CharField(choices=[('TEXTO', 'Texto'), ('EJEMPLO_PARTITURA', 'Ejemplo de partitura'), ('PRACTICA', 'Práctica'), ('IMAGEN', 'Imagen'), ('VIDEO', 'Video')], max_length=20),
        ),
    ]
