# Generated by Django 5.2.15 on 2026-09-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0032_bloquecontenido_contexto_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloquecontenido',
            name='imagen_en',
            field=models.FileField(blank=True, help_text='Versión en inglés (mismo diagrama con texto embebido en inglés, si aplica). Si queda vacío, se muestra la imagen en español también con idioma inglés activo.', null=True, upload_to='cursos_imagenes/'),
        ),
        migrations.AddField(
            model_name='bloquecontenido',
            name='video_archivo_en',
            field=models.FileField(blank=True, help_text='Versión en inglés (archivo distinto, ej. grabado o subtitulado en inglés). Si queda vacío, se muestra el video en español también con idioma inglés activo.', null=True, upload_to='cursos_videos/'),
        ),
        migrations.AddField(
            model_name='bloquecontenido',
            name='video_embed_url_en',
            field=models.CharField(blank=True, help_text='Versión en inglés (link a un video de YouTube/Vimeo distinto). Si queda vacío, se muestra el video en español también con idioma inglés activo.', max_length=500),
        ),
    ]
