# Generated by Django 5.2.15 on 2026-09-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0033_bloquecontenido_imagen_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloquecontenido',
            name='mostrar_compases_vacios_literal',
            field=models.BooleanField(default=False, help_text='Si está tildado, NO compacta compases vacíos consecutivos en un silencio grande -- los renderiza uno por uno, literal.'),
        ),
    ]
