# Generated by Django 5.2.15 on 2026-09-02 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0034_bloquecontenido_mostrar_compases_vacios_literal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bloquecontenido',
            name='modo_practica',
            field=models.CharField(blank=True, choices=[('identificar_notas', 'Identificar notas')], default='identificar_notas', help_text="Qué le pide el ejercicio al alumno. Por ahora solo 'Identificar notas' -- el campo queda abierto a sumar otros modos más adelante sin migrar de nuevo.", max_length=30),
        ),
        migrations.AddField(
            model_name='bloquecontenido',
            name='musicxml_practica',
            field=models.FileField(blank=True, help_text='MusicXML acotado (2-8 compases) para el ejercicio de práctica dirigida. Requerido cuando el tipo es Práctica dirigida.', null=True, upload_to='cursos_practica_dirigida/'),
        ),
        migrations.AddField(
            model_name='bloquecontenido',
            name='precision_minima',
            field=models.PositiveSmallIntegerField(default=80, help_text='Porcentaje de aciertos (0-100) para marcar el intento como completado. Editable por bloque por si algún tema necesita ser más permisivo.'),
        ),
        migrations.AlterField(
            model_name='bloquecontenido',
            name='tipo',
            field=models.CharField(choices=[('TEXTO', 'Texto'), ('EJEMPLO_PARTITURA', 'Ejemplo de partitura'), ('PRACTICA', 'Práctica'), ('IMAGEN', 'Imagen'), ('VIDEO', 'Video'), ('PRACTICA_DIRIGIDA', 'Práctica dirigida')], max_length=20),
        ),
        migrations.CreateModel(
            name='PracticaDirigidaProgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mejor_precision', models.FloatField(default=0)),
                ('notas_totales', models.PositiveIntegerField(default=0, help_text='Cantidad de notas del último intento.')),
                ('veces_practicado', models.PositiveIntegerField(default=0)),
                ('completado', models.BooleanField(default=False)),
                ('ultima_vez', models.DateTimeField(auto_now=True)),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.bloquecontenido')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progreso de Práctica Dirigida',
                'verbose_name_plural': 'Progresos de Práctica Dirigida',
                'unique_together': {('user', 'bloque')},
            },
        ),
    ]
