# Generated by Django 5.2.15 on 2026-09-03 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0035_bloquecontenido_modo_practica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetmusic',
            name='oculto_en_biblioteca',
            field=models.BooleanField(default=False, help_text='Para partituras subidas solo como ejemplo dentro de un curso (Ejemplo de partitura) -- no aparecen en el listado público de la Biblioteca, pero siguen funcionando normalmente donde ya estén referenciadas (el curso, favoritos, progreso).'),
        ),
    ]
