# Generated by Django 5.2.15 on 2026-09-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0036_sheetmusic_oculto_en_biblioteca'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='es_gratuito',
            field=models.BooleanField(default=False, help_text='Si está activo, el curso es accesible para cualquier usuario logueado sin compra ni suscripción -- ver pagos/access.py:tiene_acceso().'),
        ),
        migrations.AddField(
            model_name='curso',
            name='precio_ars',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio en pesos argentinos (checkout vía MercadoPago). Ignorado si es_gratuito está activo.', max_digits=10),
        ),
        migrations.AddField(
            model_name='curso',
            name='precio_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio en dólares (checkout vía PayPal). Ignorado si es_gratuito está activo.', max_digits=10),
        ),
        migrations.AddField(
            model_name='tema',
            name='es_muestra_gratuita',
            field=models.BooleanField(default=False, help_text='Si está activo, este Tema puntual es visible aunque el Curso que lo contiene no esté comprado/incluido en el plan del usuario -- ver pagos/access.py:tema_es_accesible(). Útil para dar una probada de un curso pago (ej. 2 o 3 ejercicios de muestra).'),
        ),
    ]
