# Generated by Django 5.2.15 on 2026-09-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0037_curso_es_gratuito_curso_precio_ars_curso_precio_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='mostrar_en_biblioteca',
            field=models.BooleanField(default=True, help_text='Si está destildado, esta colección no aparece como filtro en la Biblioteca de Partituras (ej. colecciones usadas solo para armar Ejemplos de partitura dentro de un Curso) -- las partituras que contiene siguen funcionando normalmente donde ya estén referenciadas.'),
        ),
    ]
