# Generated by Django 5.2.15 on 2026-09-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0038_collection_mostrar_en_biblioteca'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['orden', 'name'], 'verbose_name': 'Colección de Partituras', 'verbose_name_plural': 'Colecciones de Partituras'},
        ),
        migrations.AddField(
            model_name='collection',
            name='orden',
            field=models.IntegerField(default=0, help_text='Orden de aparición en la Biblioteca -- el número más bajo se muestra primero. Colecciones con el mismo número se ordenan entre sí por nombre.'),
        ),
    ]
