# Generated by Django 5.2.15 on 2026-09-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0039_alter_collection_options_collection_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='name_en',
            field=models.CharField(blank=True, help_text='Nombre en inglés. Si queda vacío, se muestra el español (name) también con idioma inglés activo.', max_length=100),
        ),
    ]
