# Generated by Django 5.2.15 on 2026-09-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0040_collection_name_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentoHabilitadoOrquestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Nombre mostrado en el pentagrama en blanco (ej. 'Violín I', 'Violín II') -- podés repetir el mismo rango con nombres distintos para tener varios atriles.", max_length=100)),
                ('clave_rango', models.CharField(choices=[('Flautín', 'Flautín'), ('Flauta', 'Flauta'), ('Corno Inglés', 'Corno Inglés'), ('Oboe', 'Oboe'), ('Clarinete Bajo', 'Clarinete Bajo'), ('Clarinete', 'Clarinete'), ('Contrafagot', 'Contrafagot'), ('Fagot', 'Fagot'), ('Corno', 'Corno'), ('Trompeta', 'Trompeta'), ('Trombón Bajo', 'Trombón Bajo'), ('Trombón', 'Trombón'), ('Tuba', 'Tuba'), ('Violín', 'Violín'), ('Viola', 'Viola'), ('Violonchelo', 'Violonchelo'), ('Contrabajo', 'Contrabajo'), ('Arpa', 'Arpa')], help_text='Qué entrada de RANGOS_COMODOS gobierna el rango cómodo de este instrumento.', max_length=30)),
                ('activo', models.BooleanField(default=True, help_text='Solo los activos aparecen como destino en el ejercicio.')),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Instrumento Habilitado (Orquestación)',
                'verbose_name_plural': 'Instrumentos Habilitados (Orquestación)',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PresetInstrumentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Ej. 'Orquesta de cuerdas', 'Quinteto de viento'.", max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('instrumentos', models.ManyToManyField(blank=True, related_name='presets', to='trainer.instrumentohabilitadoorquestacion')),
            ],
            options={
                'verbose_name': 'Preset de Instrumentación',
                'verbose_name_plural': 'Presets de Instrumentación',
                'ordering': ['nombre'],
            },
        ),
    ]
