# Generated by Django 5.2.15 on 2026-09-06 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0041_instrumentohabilitadoorquestacion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PresetInstrumentacion',
        ),
    ]
