# Generated by Django 5.2.15 on 2026-09-06 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0042_delete_presetinstrumentacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgresoOrquestacionLibre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignaciones', models.JSONField(blank=True, default=dict)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fragmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos_orquestacion_libre', to='trainer.fragmentoorquestacion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos_orquestacion_libre', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progreso de Orquestación Libre',
                'verbose_name_plural': 'Progresos de Orquestación Libre',
                'unique_together': {('user', 'fragmento')},
            },
        ),
    ]
