# Generated by Django 5.2.15 on 2026-09-08 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0044_bloquecontenido_ritmo_problemas_requeridos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bloquecontenido',
            name='compas_problemas_requeridos',
            field=models.PositiveSmallIntegerField(default=5, help_text='Cantidad de compases distintos a completar correctamente, en una misma tanda, para marcar el ejercicio como completado.'),
        ),
        migrations.AlterField(
            model_name='bloquecontenido',
            name='tipo',
            field=models.CharField(choices=[('TEXTO', 'Texto'), ('EJEMPLO_PARTITURA', 'Ejemplo de partitura'), ('PRACTICA', 'Práctica'), ('IMAGEN', 'Imagen'), ('VIDEO', 'Video'), ('PRACTICA_DIRIGIDA', 'Práctica dirigida'), ('RITMO_MATEMATICA', 'Ritmo matemático'), ('COMPLETAR_COMPAS', 'Completar el compás')], max_length=20),
        ),
        migrations.CreateModel(
            name='CompletarCompasProgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mejor_racha', models.PositiveSmallIntegerField(default=0)),
                ('veces_practicado', models.PositiveIntegerField(default=0)),
                ('completado', models.BooleanField(default=False)),
                ('ultima_vez', models.DateTimeField(auto_now=True)),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.bloquecontenido')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progreso de Completar el Compás',
                'verbose_name_plural': 'Progresos de Completar el Compás',
                'unique_together': {('user', 'bloque')},
            },
        ),
    ]
