# Generated by Django 5.2.15 on 2026-09-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0046_bloquecontenido_lineas_problemas_requeridos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='tipo',
            field=models.CharField(choices=[('LECTURA', 'Lectura'), ('PRACTICA', 'Práctica')], default='LECTURA', help_text='Solo determina qué tipos de bloque de contenido se ofrecen al agregar uno nuevo en este Tema (ver BloqueContenido.TIPOS_LECTURA/TIPOS_PRACTICA) -- no restringe ni valida los bloques ya existentes.', max_length=10),
        ),
        migrations.AlterField(
            model_name='bloquecontenido',
            name='tipo',
            field=models.CharField(choices=[('TEXTO', 'Texto'), ('EJEMPLO_PARTITURA', 'Ejemplo de partitura'), ('PRACTICA', 'Práctica'), ('IMAGEN', 'Imagen'), ('VIDEO', 'Video'), ('PRACTICA_DIRIGIDA', '[G0] Práctica dirigida'), ('RITMO_MATEMATICA', '[G0] Ritmo matemático'), ('COMPLETAR_COMPAS', '[G0] Completar el compás'), ('LINEAS_ESPACIOS', '[G0] Ubicación de líneas y espacios')], max_length=20),
        ),
    ]
