# Generated by Django 5.2.15 on 2026-09-10 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0047_tema_tipo_alter_bloquecontenido_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bloquecontenido',
            name='ligaduras_precision_minima',
            field=models.PositiveSmallIntegerField(default=80, help_text='Porcentaje de aciertos en ligaduras (0-100) para completar -- además hace falta marcar al menos 1 ligadura de prolongación correcta, 1 de expresión correcta, y cerrar la métrica de todos los compases con puntillos.'),
        ),
        migrations.AddField(
            model_name='bloquecontenido',
            name='musicxml_ligaduras',
            field=models.FileField(blank=True, help_text='MusicXML con compases incompletos, SIN ligaduras ni puntillos ya escritos (el ejercicio le pide al alumno agregarlos). Requerido cuando el tipo es Ligaduras y Puntillo.', null=True, upload_to='cursos_ligaduras_puntillo/'),
        ),
        migrations.AlterField(
            model_name='bloquecontenido',
            name='tipo',
            field=models.CharField(choices=[('TEXTO', 'Texto'), ('EJEMPLO_PARTITURA', 'Ejemplo de partitura'), ('PRACTICA', 'Práctica'), ('IMAGEN', 'Imagen'), ('VIDEO', 'Video'), ('PRACTICA_DIRIGIDA', '[G0] Práctica dirigida'), ('RITMO_MATEMATICA', '[G0] Ritmo matemático'), ('COMPLETAR_COMPAS', '[G0] Completar el compás'), ('LINEAS_ESPACIOS', '[G0] Ubicación de líneas y espacios'), ('LIGADURAS_PUNTILLO', '[G1] Ligaduras y Puntillo')], max_length=20),
        ),
        migrations.CreateModel(
            name='LigadurasPuntilloProgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mejor_precision', models.FloatField(default=0)),
                ('acciones_totales', models.PositiveIntegerField(default=0, help_text='Cantidad de clicks de ligadura (correctos + incorrectos) del último intento.')),
                ('veces_practicado', models.PositiveIntegerField(default=0)),
                ('completado', models.BooleanField(default=False)),
                ('ultima_vez', models.DateTimeField(auto_now=True)),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.bloquecontenido')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progreso de Ligaduras y Puntillo',
                'verbose_name_plural': 'Progresos de Ligaduras y Puntillo',
                'unique_together': {('user', 'bloque')},
            },
        ),
    ]
