# Generated by Django 5.2.15 on 2026-09-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0048_bloquecontenido_ligaduras_precision_minima_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloquecontenido',
            name='mostrar_time_signature',
            field=models.BooleanField(default=True, help_text='Si está destildado, oculta la indicación de compás (ej. 4/4) -- útil si se usa un compás de fantasía (ej. 15/1) solo para controlar el renderizado y no tiene sentido mostrarlo.'),
        ),
    ]
