# Generated by Django 5.2.15 on 2026-09-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0049_bloquecontenido_mostrar_time_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloquecontenido',
            name='mostrar_numero_compas',
            field=models.BooleanField(default=True, help_text='Si está destildado, oculta los números de compás sobre el pentagrama.'),
        ),
    ]
