# Generated by Django 5.2.15 on 2026-09-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0050_bloquecontenido_mostrar_numero_compas'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloquecontenido',
            name='mostrar_texto_staff',
            field=models.BooleanField(default=True, help_text='Si está destildado, oculta el "Staff Text" de MuseScore (Ctrl+T) -- el texto libre que se agrega arriba del pentagrama, sin ser una marca de tempo/dinámica real.'),
        ),
    ]
