# Generated by Django 5.2.15 on 2026-09-28 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0051_bloquecontenido_mostrar_texto_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloquecontenido',
            name='contexto_dividida',
            field=models.CharField(blank=True, help_text='Texto corto opcional arriba de las dos partituras, ej: "Compará estas dos versiones del mismo fragmento".', max_length=300),
        ),
        migrations.AddField(
            model_name='bloquecontenido',
            name='contexto_dividida_en',
            field=models.CharField(blank=True, help_text='Versión en inglés. Si queda vacío, se muestra el texto en español también con idioma inglés activo.', max_length=300),
        ),
        migrations.AddField(
            model_name='bloquecontenido',
            name='fragmento_orquestacion_derecha',
            field=models.ForeignKey(blank=True, help_text="Fragmento del Ejercicio de Orquestación para el panel DERECHO. Exactamente uno entre esto y 'sheet music (derecha)' cuando el tipo es Partitura pantalla dividida.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloques_curso_dividida_derecha', to='trainer.fragmentoorquestacion'),
        ),
        migrations.AddField(
            model_name='bloquecontenido',
            name='fragmento_orquestacion_izquierda',
            field=models.ForeignKey(blank=True, help_text="Fragmento del Ejercicio de Orquestación para el panel IZQUIERDO. Exactamente uno entre esto y 'sheet music (izquierda)' cuando el tipo es Partitura pantalla dividida.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloques_curso_dividida_izquierda', to='trainer.fragmentoorquestacion'),
        ),
        migrations.AddField(
            model_name='bloquecontenido',
            name='mostrar_compases_vacios_literal_dividida',
            field=models.BooleanField(default=False, help_text='Igual que en Ejemplo de partitura, aplicado a los dos paneles.'),
        ),
        migrations.AddField(
            model_name='bloquecontenido',
            name='mostrar_compositor_dividida',
            field=models.BooleanField(default=True, help_text='Igual que en Ejemplo de partitura, aplicado a los dos paneles.'),
        ),
        migrations.AddField(
            model_name='bloquecontenido',
            name='mostrar_letra_dividida',
            field=models.BooleanField(default=True, help_text='Igual que en Ejemplo de partitura, aplicado a los dos paneles.'),
        ),
        migrations.AddField(
            model_name='bloquecontenido',
            name='mostrar_nombre_instrumento_dividida',
            field=models.BooleanField(default=True, help_text='Igual que en Ejemplo de partitura, pero aplicado a los DOS paneles de este bloque por igual.'),
        ),
        migrations.AddField(
            model_name='bloquecontenido',
            name='mostrar_numero_compas_dividida',
            field=models.BooleanField(default=True, help_text='Igual que en Ejemplo de partitura, aplicado a los dos paneles.'),
        ),
        migrations.AddField(
            model_name='bloquecontenido',
            name='mostrar_texto_staff_dividida',
            field=models.BooleanField(default=True, help_text='Igual que en Ejemplo de partitura, aplicado a los dos paneles.'),
        ),
        migrations.AddField(
            model_name='bloquecontenido',
            name='mostrar_time_signature_dividida',
            field=models.BooleanField(default=True, help_text='Igual que en Ejemplo de partitura, aplicado a los dos paneles.'),
        ),
        migrations.AddField(
            model_name='bloquecontenido',
            name='sheet_music_derecha',
            field=models.ForeignKey(blank=True, help_text="Partitura de la Biblioteca para el panel DERECHO. Exactamente una entre esto y 'fragmento orquestación (derecha)' cuando el tipo es Partitura pantalla dividida.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloques_curso_dividida_derecha', to='trainer.sheetmusic'),
        ),
        migrations.AddField(
            model_name='bloquecontenido',
            name='sheet_music_izquierda',
            field=models.ForeignKey(blank=True, help_text="Partitura de la Biblioteca para el panel IZQUIERDO. Exactamente una entre esto y 'fragmento orquestación (izquierda)' cuando el tipo es Partitura pantalla dividida.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloques_curso_dividida_izquierda', to='trainer.sheetmusic'),
        ),
        migrations.AlterField(
            model_name='bloquecontenido',
            name='tipo',
            field=models.CharField(choices=[('TEXTO', 'Texto'), ('EJEMPLO_PARTITURA', 'Ejemplo de partitura'), ('PARTITURA_DIVIDIDA', 'Partitura pantalla dividida'), ('PRACTICA', 'Práctica'), ('IMAGEN', 'Imagen'), ('VIDEO', 'Video'), ('PRACTICA_DIRIGIDA', '[G0] Práctica dirigida'), ('RITMO_MATEMATICA', '[G0] Ritmo matemático'), ('COMPLETAR_COMPAS', '[G0] Completar el compás'), ('LINEAS_ESPACIOS', '[G0] Ubicación de líneas y espacios'), ('LIGADURAS_PUNTILLO', '[G1] Ligaduras y Puntillo')], max_length=20),
        ),
    ]
