# Generated by Django 5.2.15 on 2026-10-04 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0052_bloquecontenido_contexto_dividida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='pdf_contratapa',
            field=models.FileField(blank=True, help_text='Imagen de contratapa (PNG o JPG), última página del PDF exportado. Si queda vacío, el PDF no la incluye.', null=True, upload_to='cursos_pdf/'),
        ),
        migrations.AddField(
            model_name='curso',
            name='pdf_portada',
            field=models.FileField(blank=True, help_text='Imagen de tapa (PNG o JPG) para el PDF exportado del curso. Si queda vacío, el PDF arranca directo con el título.', null=True, upload_to='cursos_pdf/'),
        ),
        migrations.CreateModel(
            name='CursoPdfPagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(choices=[('CREDITOS', 'Antes del índice (créditos/agradecimientos)'), ('CIERRE', 'Al final del libro (cierre)')], default='CREDITOS', max_length=10)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden dentro de su ubicación -- las páginas de una misma ubicación se muestran ordenadas por esto.')),
                ('texto_markdown', models.TextField(help_text='Fuente Markdown -- mismo renderizado/sanitización que un bloque de Texto (ver BloqueContenido.texto_markdown).')),
                ('texto_markdown_en', models.TextField(blank=True, help_text='Versión en inglés. Si queda vacío, se muestra el texto en español también con idioma inglés activo.')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paginas_pdf', to='trainer.curso')),
            ],
            options={
                'verbose_name': 'Página de PDF (créditos/cierre)',
                'verbose_name_plural': 'Páginas de PDF (créditos/cierre)',
                'ordering': ['curso', 'ubicacion', 'orden'],
            },
        ),
    ]
