# Generated by Django 5.2.15 on 2026-10-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0053_curso_pdf_contratapa_curso_pdf_portada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='pdf_contratapa_en',
            field=models.FileField(blank=True, help_text='Versión en inglés de la contratapa. Si queda vacío, se usa la contratapa en español también con idioma inglés activo.', null=True, upload_to='cursos_pdf/'),
        ),
        migrations.AddField(
            model_name='curso',
            name='pdf_portada_en',
            field=models.FileField(blank=True, help_text='Versión en inglés de la tapa. Si queda vacío, se usa la tapa en español también con idioma inglés activo.', null=True, upload_to='cursos_pdf/'),
        ),
    ]
