# Generated by Django 5.2.15 on 2026-10-05 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0054_curso_pdf_contratapa_en_curso_pdf_portada_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='pdf_contratapa',
            field=models.FileField(blank=True, help_text='Imagen de contratapa (PNG o JPG), última página del PDF exportado -- misma proporción 1:1,4142 que pdf_portada (ver ese campo). Si queda vacío, el PDF no la incluye.', null=True, upload_to='cursos_pdf/'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='pdf_portada',
            field=models.FileField(blank=True, help_text='Imagen de tapa (PNG o JPG) para el PDF exportado del curso. Se estira para cubrir la hoja A4 entera, de punta a punta (sin margen) -- preparar el archivo en proporción 1:1,4142 (igual que cualquier hoja ISO, ej. 1414x2000px o 2480x3508px) para que no se vea deformada. Si queda vacío, el PDF arranca directo con el título.', null=True, upload_to='cursos_pdf/'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='pdf_portada_en',
            field=models.FileField(blank=True, help_text='Versión en inglés de la tapa (misma proporción 1:1,4142 que pdf_portada). Si queda vacío, se usa la tapa en español también con idioma inglés activo.', null=True, upload_to='cursos_pdf/'),
        ),
    ]
