# Generated by Django 5.2.15 on 2026-10-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0055_alter_curso_pdf_contratapa_alter_curso_pdf_portada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentohabilitadoorquestacion',
            name='clave_rango',
            field=models.CharField(choices=[('Flautín', 'Flautín'), ('Flauta', 'Flauta'), ('Flauta Alto', 'Flauta Alto'), ('Flauta Bajo', 'Flauta Bajo'), ('Corno Inglés', 'Corno Inglés'), ('Oboe', 'Oboe'), ('Clarinete Bajo', 'Clarinete Bajo'), ('Clarinete', 'Clarinete'), ('Contrafagot', 'Contrafagot'), ('Fagot', 'Fagot'), ('Saxo Soprano', 'Saxo Soprano'), ('Saxo Alto', 'Saxo Alto'), ('Saxo Tenor', 'Saxo Tenor'), ('Saxo Barítono', 'Saxo Barítono'), ('Corno', 'Corno'), ('Trompeta', 'Trompeta'), ('Trombón Bajo', 'Trombón Bajo'), ('Trombón', 'Trombón'), ('Tuba', 'Tuba'), ('Violín', 'Violín'), ('Viola', 'Viola'), ('Violonchelo', 'Violonchelo'), ('Contrabajo', 'Contrabajo'), ('Arpa', 'Arpa'), ('Piano', 'Piano'), ('Guitarra', 'Guitarra'), ('Xilófono', 'Xilófono'), ('Marimba', 'Marimba'), ('Vibráfono', 'Vibráfono'), ('Glockenspiel', 'Glockenspiel'), ('Timbal', 'Timbal'), ('Soprano', 'Soprano'), ('Mezzosoprano', 'Mezzosoprano'), ('Contralto', 'Contralto'), ('Tenor', 'Tenor'), ('Barítono', 'Barítono'), ('Bajo', 'Bajo')], help_text='Qué entrada de RANGOS_COMODOS gobierna el rango cómodo de este instrumento.', max_length=30),
        ),
    ]
