# Generated by Django 5.2.15 on 2026-10-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0056_alter_instrumentohabilitadoorquestacion_clave_rango'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreanalysis',
            name='tiempo_generacion_segundos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoreanalysis',
            name='tokens_por_segundo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
