"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#
# Deliberadamente SIN default -- un valor por defecto acá (aunque tenga el prefijo
# "django-insecure-" que genera el propio startproject de Django) queda commiteado al
# repo, legible por cualquiera que lo lea. Con esa clave se firman cookies de sesión,
# tokens de reseteo de contraseña y el token CSRF -- filtrada, se pueden forjar todos
# esos. A diferencia de SCORE_FILE_ENCRYPTION_KEY (que falla recién al primer uso,
# porque el resto del sitio funciona sin ella), acá el fallo tiene que ser inmediato:
# Django necesita SECRET_KEY para arrancar, no hay "resto del sitio" que funcione sin
# esto.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY no está configurada. Nunca debe tener un valor por "
        "default en el código -- generar una clave real y cargarla como variable "
        "de entorno (local y en la configuración de la app web de PythonAnywhere). "
        "Generación: python -c \"from django.core.management.utils import "
        "get_random_secret_key; print(get_random_secret_key())\""
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'ripp76.pythonanywhere.com']

# ==============================================================================
# CLAVE DE CIFRADO DE ARCHIVOS DEL ANALIZADOR (trainer.storage.EncryptedFileSystemStorage)
#
# Cifra en reposo los MusicXML/MIDI que suben los usuarios al Analizador de
# Partituras. NO tiene (ni debe tener) un valor por defecto: a diferencia de
# SECRET_KEY, si esta variable falta el analizador debe fallar ruidosamente al
# guardar/leer un archivo, nunca degradar en silencio a texto plano.
#
# ADVERTENCIA — PERDER ESTA CLAVE ES IRREVERSIBLE: sin ella, absolutamente
# ningún archivo ya cifrado con Fernet se puede volver a leer. No existe
# recuperación posible, ni por soporte de Anthropic ni de nadie.
#
# Generación y manejo (fuera de este repositorio, nunca en código ni en git):
#   1. Generar una vez:
#        python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
#   2. Guardar esa clave en un gestor de contraseñas o backup seguro propio.
#   3. Recién después, cargarla como variable de entorno SCORE_FILE_ENCRYPTION_KEY
#      (en local y en la configuración de la app web de PythonAnywhere).
# ==============================================================================
SCORE_FILE_ENCRYPTION_KEY = os.environ.get('SCORE_FILE_ENCRYPTION_KEY')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'trainer',
    # Excepción puntual y documentada a la convención de "un solo app" de este proyecto
    # -- ver la sección "Excepción a la convención de un solo app: pagos/" en CLAUDE.md
    # para la justificación completa (credenciales de proveedores externos, webhooks sin
    # sesión de Django, bugs que cuestan plata real). trainer/ sigue siendo el único app
    # para todo lo demás.
    'pagos',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Entre Session y Common -- orden exigido por Django (necesita la sesión ya
    # resuelta para leer el idioma guardado, y tiene que correr antes que
    # Common para poder actuar sobre la URL con prefijo de idioma).
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

# Django SIEMPRE envuelve los loaders por default en cached.Loader (ver
# django/template/engine.py: pasa exactamente igual con APP_DIRS=True sin
# 'loaders' explícito) -- independientemente de DEBUG. Ese cache es un dict en
# memoria de proceso que nunca se invalida por mtime, solo con un restart real
# del proceso. Contradice un supuesto que este proyecto daba por cierto ("con
# DEBUG=True no cachea") -- confirmado leyendo el traceback real de un
# TemplateSyntaxError que pasaba por django/template/loaders/cached.py pese a
# DJANGO_DEBUG=True, no asumido. En DEBUG se fuerzan los loaders sin el
# wrapper cacheado para que runserver reeleje templates en cada request sin
# necesitar reiniciar el proceso a mano; en producción (DEBUG=False) se deja
# el comportamiento default de Django (cacheado, mejor para performance) --
# ahí el Reload de PythonAnywhere sigue siendo necesario igual que siempre,
# eso no cambia.
_TEMPLATE_OPTIONS = {
    'context_processors': [
        'django.template.context_processors.request',
        'django.contrib.auth.context_processors.auth',
        'django.contrib.messages.context_processors.messages',
        # Expone LANGUAGE_CODE/LANGUAGES en todos los templates sin
        # necesitar {% get_current_language %} en cada uno.
        'django.template.context_processors.i18n',
    ],
}
if DEBUG:
    _TEMPLATE_OPTIONS['loaders'] = [
        'django.template.loaders.filesystem.Loader',
        'django.template.loaders.app_directories.Loader',
    ]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        # APP_DIRS y 'loaders' son mutuamente excluyentes para Django (levanta
        # ImproperlyConfigured si se dan los dos) -- por eso va en False acá y
        # app_directories.Loader se agrega a mano en _TEMPLATE_OPTIONS arriba.
        'APP_DIRS': not DEBUG,
        'OPTIONS': _TEMPLATE_OPTIONS,
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# Antes 'en-us' -- descuido preexistente sin relación con el soporte de i18n
# (grep del proyecto entero confirmó que ningún otro código dependía de ese
# valor literal). Español es el idioma real por default del sitio.
LANGUAGE_CODE = 'es'

LANGUAGES = [
    ('es', 'Español'),
    ('en', 'English'),
]

LOCALE_PATHS = [BASE_DIR / 'locale']

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/login/'
LOGOUT_REDIRECT_URL = '/login/'


# ==============================================================================
# COOKIES SEGURAS + REDIRECT HTTPS (solo en producción)
#
# Condicionado a `not DEBUG` para no romper runserver local (sin HTTPS local,
# SECURE_SSL_REDIRECT=True en dev dejaría al desarrollador afuera de su propio sitio).
#
# SECURE_PROXY_SSL_HEADER es el que evita un loop de redirect en PythonAnywhere: su
# proxy termina TLS y le habla a Django por HTTP plano puertas adentro -- sin este
# header, Django ve cada request como HTTP puro, SECURE_SSL_REDIRECT lo manda a
# redirigir a HTTPS, PythonAnywhere lo vuelve a mandar por HTTP interno, y así en
# bucle. Confiar en este header solo tiene sentido porque PythonAnywhere es quien
# controla el proxy que lo setea -- si el deploy cambiara a otro proveedor sin este
# mismo comportamiento de proxy, este header dejaría de ser confiable y habría que
# revisarlo de nuevo.
# ==============================================================================
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# ==============================================================================
# ADMINS / EMAIL -- alertas de pagos/webhooks.py (ver "Visibilidad sobre webhooks
# fallidos" en el plan que introdujo pagos/) y, como efecto colateral positivo, el email
# automático que Django ya sabe mandar ante cualquier error 500 con DEBUG=False (algo
# que este proyecto no tenía para NADA del sitio hasta ahora, no solo pagos).
#
# Todo opcional, con degradación sin crash -- mismo patrón que ANTHROPIC_TEST_API_KEY:
# sin DJANGO_ADMIN_EMAILS configurada, ADMINS queda vacío y mail_admins()/el email de
# error 500 simplemente no hacen nada (no hay excepción, no hay 500 en la carga del
# sitio). Nadie debería necesitar SMTP configurado para correr runserver/test.
# ==============================================================================
_admin_emails = os.environ.get('DJANGO_ADMIN_EMAILS', '')
ADMINS = [(f"Admin {i+1}", email.strip()) for i, email in enumerate(_admin_emails.split(',')) if email.strip()]
MANAGERS = ADMINS

EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'no-reply@musica-digital.local')
SERVER_EMAIL = DEFAULT_FROM_EMAIL
# Sin EMAIL_HOST configurado, Django intentaría conectar a localhost:25 y fallar --
# se degrada a la consola en vez de eso (mail_admins() sigue "funcionando", solo
# imprime a stdout en vez de mandar de verdad; el try/except alrededor de mail_admins()
# en pagos/webhooks.py cubre igual el caso de que EMAIL_HOST SÍ esté configurado pero el
# envío falle en runtime por cualquier otro motivo).
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' if EMAIL_HOST else 'django.core.mail.backends.console.EmailBackend'
