"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#
# Deliberadamente SIN default -- un valor por defecto acá (aunque tenga el prefijo
# "django-insecure-" que genera el propio startproject de Django) queda commiteado al
# repo, legible por cualquiera que lo lea. Con esa clave se firman cookies de sesión,
# tokens de reseteo de contraseña y el token CSRF -- filtrada, se pueden forjar todos
# esos. A diferencia de SCORE_FILE_ENCRYPTION_KEY (que falla recién al primer uso,
# porque el resto del sitio funciona sin ella), acá el fallo tiene que ser inmediato:
# Django necesita SECRET_KEY para arrancar, no hay "resto del sitio" que funcione sin
# esto.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY no está configurada. Nunca debe tener un valor por "
        "default en el código -- generar una clave real y cargarla como variable "
        "de entorno (local y en la configuración de la app web de PythonAnywhere). "
        "Generación: python -c \"from django.core.management.utils import "
        "get_random_secret_key; print(get_random_secret_key())\""
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'ripp76.pythonanywhere.com']

# ==============================================================================
# CLAVE DE CIFRADO DE ARCHIVOS DEL ANALIZADOR (trainer.storage.EncryptedFileSystemStorage)
#
# Cifra en reposo los MusicXML/MIDI que suben los usuarios al Analizador de
# Partituras. NO tiene (ni debe tener) un valor por defecto: a diferencia de
# SECRET_KEY, si esta variable falta el analizador debe fallar ruidosamente al
# guardar/leer un archivo, nunca degradar en silencio a texto plano.
#
# ADVERTENCIA — PERDER ESTA CLAVE ES IRREVERSIBLE: sin ella, absolutamente
# ningún archivo ya cifrado con Fernet se puede volver a leer. No existe
# recuperación posible, ni por soporte de Anthropic ni de nadie.
#
# Generación y manejo (fuera de este repositorio, nunca en código ni en git):
#   1. Generar una vez:
#        python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
#   2. Guardar esa clave en un gestor de contraseñas o backup seguro propio.
#   3. Recién después, cargarla como variable de entorno SCORE_FILE_ENCRYPTION_KEY
#      (en local y en la configuración de la app web de PythonAnywhere).
# ==============================================================================
SCORE_FILE_ENCRYPTION_KEY = os.environ.get('SCORE_FILE_ENCRYPTION_KEY')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'trainer',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/login/'
LOGOUT_REDIRECT_URL = '/login/'


# ==============================================================================
# COOKIES SEGURAS + REDIRECT HTTPS (solo en producción)
#
# Condicionado a `not DEBUG` para no romper runserver local (sin HTTPS local,
# SECURE_SSL_REDIRECT=True en dev dejaría al desarrollador afuera de su propio sitio).
#
# SECURE_PROXY_SSL_HEADER es el que evita un loop de redirect en PythonAnywhere: su
# proxy termina TLS y le habla a Django por HTTP plano puertas adentro -- sin este
# header, Django ve cada request como HTTP puro, SECURE_SSL_REDIRECT lo manda a
# redirigir a HTTPS, PythonAnywhere lo vuelve a mandar por HTTP interno, y así en
# bucle. Confiar en este header solo tiene sentido porque PythonAnywhere es quien
# controla el proxy que lo setea -- si el deploy cambiara a otro proveedor sin este
# mismo comportamiento de proxy, este header dejaría de ser confiable y habría que
# revisarlo de nuevo.
# ==============================================================================
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
