from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('perfil/', views.perfil, name='perfil'),
    path('entrenador/', views.entrenador_index, name='entrenador_index'),
    path('juego/notas/', views.trainer_notas, name='trainer_notas'),
    path('juego/intervalos/', views.trainer_intervalos, name='trainer_intervalos'),
    path('juego/intervalos-auditivos/', views.trainer_intervalos_auditivos, name='trainer_intervalos_auditivos'),
    path('juego/dictado-melodico/', views.trainer_dictado_melodico, name='trainer_dictado_melodico'),
    path('juego/lectura-musical/', views.trainer_lectura_musical, name='trainer_lectura_musical'),
    path('juego/tiempos-fuertes-debiles/', views.trainer_tiempos_fuertes_debiles, name='trainer_tiempos_fuertes_debiles'),
    path('juego/sincopas-contratiempos/', views.trainer_sincopas_contratiempos, name='trainer_sincopas_contratiempos'),
    path('juego/reconocimiento-acordes/', views.trainer_reconocimiento_acordes, name='trainer_reconocimiento_acordes'),
    path('juego/analisis-progresiones/', views.trainer_analisis_progresiones, name='trainer_analisis_progresiones'),
    path('biblioteca/', views.biblioteca_list, name='biblioteca_list'),
    path('biblioteca/<int:score_id>/', views.biblioteca_play, name='biblioteca_play'),
    path('api/record_attempt/<str:game_slug>/', views.record_attempt, name='record_attempt'),
    path('api/toggle_favorite/<int:score_id>/', views.toggle_favorite, name='toggle_favorite'),
    path('api/log_study_session/', views.log_study_session, name='log_study_session'),
    path('api/add_sheet_marker/<int:score_id>/', views.add_sheet_marker, name='add_sheet_marker'),
    path('api/add_sheet_note/<int:score_id>/', views.add_sheet_note, name='add_sheet_note'),
    path('playlists/', views.playlists_list, name='playlists_list'),
    path('api/playlist_add_sheet/', views.playlist_add_sheet, name='playlist_add_sheet'),
    path('api/save_rehearsal_config/<int:score_id>/', views.save_rehearsal_config, name='save_rehearsal_config'),
    path('api/log_rehearsal_session/<int:score_id>/', views.log_rehearsal_session, name='log_rehearsal_session'),
    path('register/', views.register, name='register'),
    path('proyectos/', views.proyectos_list, name='proyectos_list'),
    path('proyectos/<int:project_id>/', views.proyecto_detail, name='proyecto_detail'),
    path('api/create_project/<int:score_id>/', views.api_create_project, name='api_create_project'),
    path('api/update_project_state/<int:project_id>/', views.api_update_project_state, name='api_update_project_state'),
    path('api/update_project_section/<int:project_id>/', views.api_update_project_section, name='api_update_project_section'),
    path('midi-trainer/', views.midi_trainer_hub, name='midi_trainer_hub'),
    path('midi-trainer/juego/acordes/', views.midi_game_chords, name='midi_game_chords'),
    path('api/log_midi_game/', views.api_log_midi_game, name='api_log_midi_game'),
]
